import 'package:coffeeapp/model/coffee_model.dart';

List<CoffeeModel> coffeeData = [
  CoffeeModel(
    code: 1,
    name: 'Cappuccino',
    category: 'Hot Coffee',
    type: 'Coffee',
    image: 'https://i.pinimg.com/1200x/cf/20/0f/cf200fcd889e35ea0911e3195c705f8f.jpg',
    des: 'A cappuccino is an espresso-based coffee drink topped with steamed milk foam.',
    instruction: 'Sugar 50%',
    price: 2.5,
    favorite: false,
    size: ['S', 'M', 'L'],
  ),
  CoffeeModel(
    code: 2,
    name: 'Latte',
    category: 'Hot Coffee',
    type: 'Coffee',
    image: 'https://i.pinimg.com/736x/ad/e9/ad/ade9ad2b023c1b67b36fb2b322427334.jpg',
    des: 'A latte is made with espresso and steamed milk with a smooth and creamy taste.',
    instruction: 'Sugar 50%',
    price: 3.0,
    favorite: false,
    size: ['S', 'M', 'L'],
  ),
  CoffeeModel(
    code: 3,
    name: 'Mocha',
    category: 'Hot Coffee',
    type: 'Coffee',
    image: 'https://sweetphi.com/wp-content/uploads/2021/03/Mocha-recipe-made-with-hot-cocoa-mix-3-scaled.jpg',
    des: 'A mocha is a delicious coffee drink combining espresso, chocolate, and steamed milk.',
    instruction: 'Sugar 50%',
    price: 3.5,
    favorite: false,
    size: ['S', 'M', 'L'],
  ),
  CoffeeModel(
    code: 4,
    name: 'Americano',
    category: 'Hot Coffee',
    type: 'Coffee',
    image: 'https://t4.ftcdn.net/jpg/05/38/37/53/360_F_538375332_06IbJscMAhJ8aTF5iIEGMIBxBDyvlJbb.jpg',
    des: 'An Americano is prepared by combining espresso with hot water for a smooth coffee flavor.',
    instruction: 'Sugar 25%',
    price: 2.0,
    favorite: false,
    size: ['S', 'M', 'L'],
  ),
  CoffeeModel(
    code: 5,
    name: 'Espresso',
    category: 'Hot Coffee',
    type: 'Coffee',
    image: 'https://i.pinimg.com/736x/2f/76/58/2f76584f39911bfa99ac659c4d7b5e67.jpg',
    des: 'Espresso is a concentrated coffee brewed by forcing hot water through finely ground coffee.',
    instruction: 'No Sugar',
    price: 1.8,
    favorite: false,
    size: ['S', 'M'],
  ),
  CoffeeModel(
    code: 6,
    name: 'Flat White',
    category: 'Hot Coffee',
    type: 'Coffee',
    image: 'https://i.pinimg.com/1200x/2d/9e/ed/2d9eedb5cee67febb093543e712a5d6a.jpg',
    des: 'A flat white combines espresso with steamed milk to create a rich and velvety coffee.',
    instruction: 'Sugar 25%',
    price: 3.2,
    favorite: false,
    size: ['S', 'M', 'L'],
  ),
  CoffeeModel(
    code: 7,
    name: 'Macchiato',
    category: 'Hot Coffee',
    type: 'Coffee',
    image: 'https://i.pinimg.com/1200x/42/ac/77/42ac77f6d95fae0ab95a6ab6bae8f6e7.jpg',
    des: 'A macchiato is an espresso topped with a small amount of steamed milk foam.',
    instruction: 'Sugar 25%',
    price: 2.8,
    favorite: false,
    size: ['S', 'M'],
  ),
  CoffeeModel(
    code: 8,
    name: 'Caramel Latte',
    category: 'Hot Coffee',
    type: 'Coffee',
    image: 'https://i.pinimg.com/1200x/db/44/51/db44511c3ad105707862b08f9bd34c7d.jpg',
    des: 'A creamy latte flavored with sweet caramel syrup and topped with milk foam.',
    instruction: 'Sugar 75%',
    price: 3.8,
    favorite: false,
    size: ['S', 'M', 'L'],
  ),
  CoffeeModel(
    code: 9,
    name: 'Vanilla Latte',
    category: 'Hot Coffee',
    type: 'Coffee',
    image: 'https://i.pinimg.com/1200x/54/f3/41/54f3419cc799c2c0afb3c1ab19adcb53.jpg',
    des: 'A smooth latte blended with sweet vanilla syrup for a rich and fragrant flavor.',
    instruction: 'Sugar 75%',
    price: 3.6,
    favorite: false,
    size: ['S', 'M', 'L'],
  ),
  CoffeeModel(
    code: 10,
    name: 'Iced Coffee',
    category: 'Cold Coffee',
    type: 'Coffee',
    image: 'https://i.pinimg.com/736x/cf/dc/72/cfdc726d42d4e0bae2aecec1ed8ccd2e.jpg',
    des: 'Iced coffee is brewed coffee served chilled with ice for a refreshing taste.',
    instruction: 'Sugar 50%',
    price: 2.5,
    favorite: false,
    size: ['S', 'M', 'L'],
  ),
  CoffeeModel(
    code: 11,
    name: 'Iced Latte',
    category: 'Cold Coffee',
    type: 'Coffee',
    image: 'https://i.pinimg.com/736x/c6/20/a4/c620a4af6ab203cd97458b35c6eb85a9.jpg',
    des: 'Iced latte is made with espresso, cold milk, and ice for a refreshing creamy drink.',
    instruction: 'Sugar 50%',
    price: 3.2,
    favorite: false,
    size: ['S', 'M', 'L'],
  ),
  CoffeeModel(
    code: 12,
    name: 'Iced Mocha',
    category: 'Cold Coffee',
    type: 'Coffee',
    image: 'https://i.pinimg.com/1200x/5b/bc/ca/5bbcca02aab84d19d1b6a72e21bc84a8.jpg',
    des: 'Iced mocha combines espresso, chocolate, cold milk, and ice for a sweet coffee drink.',
    instruction: 'Sugar 75%',
    price: 3.8,
    favorite: false,
    size: ['S', 'M', 'L'],
  ),
  CoffeeModel(
    code: 13,
    name: 'Cold Brew',
    category: 'Cold Coffee',
    type: 'Coffee',
    image: 'https://i.pinimg.com/1200x/6a/aa/3a/6aaa3aaab1b40db6a04b59545d7bb4ca.jpg',
    des: 'Cold brew coffee is slowly brewed with cold water to create a smooth and less acidic taste.',
    instruction: 'No Sugar',
    price: 3.5,
    favorite: false,
    size: ['S', 'M', 'L'],
  ),
  CoffeeModel(
    code: 14,
    name: 'Matcha Latte',
    category: 'Hot Drink',
    type: 'Non-Coffee',
    image: 'https://i.pinimg.com/736x/62/3e/eb/623eeb284d950d54586d6845b3fcd678.jpg',
    des: 'Matcha latte is a creamy drink made with Japanese green tea powder and steamed milk.',
    instruction: 'Sugar 50%',
    price: 3.5,
    favorite: false,
    size: ['S', 'M', 'L'],
  ),
  CoffeeModel(
    code: 15,
    name: 'Chocolate Latte',
    category: 'Hot Drink',
    type: 'Non-Coffee',
    image: 'https://i.pinimg.com/736x/ee/6c/0d/ee6c0d703e6b2fc634a2986392019495.jpg',
    des: 'A creamy chocolate drink made with milk and rich chocolate flavor.',
    instruction: 'Sugar 75%',
    price: 3.0,
    favorite: false,
    size: ['S', 'M', 'L'],
  ),
];


